FROM archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
    base-devel \
    cmake \
    git \
    vulkan-icd-loader \
    vulkan-headers \
    shaderc \
    && pacman -Scc --noconfirm

COPY scripts/build-llama.sh /usr/bin/build-llama
COPY scripts/build-llama-vulkan.sh /usr/bin/build-llama-vulkan
RUN chmod +x /usr/bin/build-llama /usr/bin/build-llama-vulkan

WORKDIR /root
CMD ["/usr/bin/build-llama"]
