FROM fedora:latest

RUN dnf install -y --refresh --nogpgcheck \
    gcc-c++ \
    cmake \
    git \
    vulkan-loader-devel \
    vulkan-headers \
    shaderc \
    shaderc-devel \
    && dnf clean all

COPY scripts/build-llama.sh /usr/bin/build-llama
COPY scripts/build-llama-vulkan.sh /usr/bin/build-llama-vulkan
RUN chmod +x /usr/bin/build-llama /usr/bin/build-llama-vulkan

WORKDIR /root
CMD ["/usr/bin/build-llama"]
